---
title: "vis_2"
author: "Hanrui Li"
date: "2024-10-01"
output: github_document
---

```{r message=FALSE}
library(tidyverse)
library(patchwork)
```

```{r message=FALSE, warning=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

weather_df
```

```{r message=FALSE, warning=FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```

```{r message=FALSE, warning=FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stationns."
  )
```

Scales -- start with `x` and `y`

```{r message=FALSE, warning=FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stationns."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 20),
    labels = c("-15C", "0", "20")
  ) +
  scale_y_continuous(
    limits = c(0, 30),
    transform = "sqrt"
  )
```


Look at color:

```{r message=FALSE, warning=FALSE}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stationns."
  ) +
  viridis::scale_color_viridis(discrete = TRUE)

```


# Themes

```{r message=FALSE, warning=FALSE}
ggp_scatterplot =
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  labs(
    title = "Temperature Scatterplot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stationns."
  ) +
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r message=FALSE, warning=FALSE}
ggp_scatterplot +
  theme(legend.position = "bottom")
```

```{r message=FALSE, warning=FALSE}
ggp_scatterplot + 
  theme_bw() +
  theme(legend.position = "bottom")
```

```{r message=FALSE, warning=FALSE}
ggp_scatterplot + 
  theme(legend.position = "bottom") + 
  theme_minimal()
```

```{r message=FALSE, warning=FALSE}
ggp_scatterplot + 
  theme(legend.position = "bottom") +
  theme_classic()
```

```{r message=FALSE, warning=FALSE}
ggp_scatterplot + 
  theme(legend.position = "bottom") + 
  ggthemes::theme_excel() 
```

New scatterplot

```{r message=FALSE, warning=FALSE}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_smooth(se = FALSE) +
  viridis::scale_color_viridis(discrete = TRUE) +
  labs(
    x = "Date",
    y = "Maximum Temp (C)",
    title = "Seasonal variation in Max Temp",
    size = "Precipitation"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

Extra bonus stuff in `ggplot`

Use different datasets in different `geom`s

```{r message=FALSE, warning=FALSE}
central_park_df =
  weather_df |>
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df |>
  filter(name == "Molokai_HI")

molokai_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park_df)
```



## Multiple panels

```{r message=FALSE, warning=FALSE}
weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_density() +
  facet_grid(. ~ name)
```

# `patchwork`

```{r message=FALSE, warning=FALSE}
ggp_tmax_tmin = 
  weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point(alpha = .3)

ggp_tmax_density = 
  weather_df |>
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)

ggp_tmax_tmin + ggp_tmax_density

ggp_tmax_date = 
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE)

(ggp_tmax_tmin + ggp_tmax_density) / ggp_tmax_date
```

## Data manipulation

```{r message=FALSE, warning=FALSE}
weather_df |>
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = .5)

weather_df |> 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |>
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = .5)
```


PULSE data next.

```{r message=FALSE, warning=FALSE}
library(haven)

pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  mutate(visit = ifelse(visit == "bl", "00m", visit))

pulse_df |>
  ggplot(aes(x = visit, y = bdi_score)) +
  geom_boxplot()
```

FAS data.

```{r message=FALSE, warning=FALSE}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "tx_day"), sep = 3)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day",
    names_prefix = "pd_"
  )

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")

fas_df |> 
  drop_na(tx_day) |>
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_boxplot() + 
  facet_grid(tx_day ~ outcome)
```









