---
title: "vis_3_eda"
author: "Hanrui Li"
date: "2024-10-03"
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r message=FALSE, warning=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())
```

Make some plots:

Initial numeric explorations

```{r message=FALSE, warning=FALSE}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp > 1000) |>
  knitr::kable()
```

```{r}
weather_df |> 
  filter(tmax > 20, tmax < 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```

## `group_by()`

```{r}
weather_df |>
  group_by(name)

weather_df |>
  group_by(name, month)
```

Counting stuff in a group:

```{r}
weather_df |>
  group_by(name) |>
  summarise(n_obs = n()) |>
  knitr::kable()
```

```{r message=FALSE}
weather_df |>
  group_by(name) |>
  summarise(
    n_obs = n(),
    n_dist = n_distinct(month)
  ) |>
  knitr::kable()

weather_df |>
  group_by(name, month) |>
  summarise(
    n_obs = n()
  )
```

## $2\times2$ table

```{r message=FALSE}
weather_df |>
  drop_na(tmax) |>
  filter(name != "Molokai_HI") |>
  mutate(
    cold = case_when(
      tmin < 5 ~ "cold",
      tmax >= 5 ~ "not cold"
    )
  ) |>
  group_by(name, cold) |>
  summarise(count = n()) |>
  knitr::kable()
```

```{r}
weather_df |>
  drop_na(tmax) |>
  filter(name != "Molokai_HI") |>
  mutate(
    cold = case_when(
      tmin < 5 ~ "cold",
      tmax >= 5 ~ "not cold"
    )
  ) |>
  janitor::tabyl(name, cold)
```

General numeric summaries:

```{r}
weather_df |>
  group_by(name) |>
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |>
  knitr::kable()
```

```{r message=FALSE}
weather_df |>
  group_by(name, month) |>
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

Create a plot based on the monthly summary:

```{r message=FALSE}
weather_df |>
  group_by(name, month) |>
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  ) |>
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

Format for readers:

```{r message=FALSE}
weather_df |>
  group_by(name, month) |>
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |>
  knitr::kable(
    digits = 3,
    col.names = c("Month", "Central Park", "Molokai", "Waterhole"))
```

## Grouped mutates

```{r}
weather_df |>
  group_by(name) |>
  mutate(mean_tmax = mean(tmax, na.rm = TRUE))
```

```{r message=FALSE, warning=FALSE}
weather_df |>
  group_by(name) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) |>
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

Find hottest / coldest days:

```{r}
weather_df |>
  mutate(
    temp_rank = min_rank(tmax)
  ) |>
  filter(temp_rank < 10) |>
  knitr::kable()
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    temp_rank = min_rank(tmax)
  ) |>
  filter(temp_rank < 4) |>
  knitr::kable()
```

`desc()` descending functionn:

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    temp_rank = min_rank(desc(tmax))
  ) |>
  filter(temp_rank < 4) |>
  knitr::kable()
```

```{r}
weather_df |>
  group_by(name) |>
  filter(min_rank(tmax) < 4) |>
  arrange(tmax) |>
  knitr::kable()
```

`lag` function:

```{r}
weather_df |>
  mutate(
    lagged_temp = lag(tmax)
  )

weather_df |>
  group_by(name) |>
  mutate(
    lagged_temp = lag(tmax),
    temp_change = tmax - lagged_temp
  ) |>
  filter(min_rank(temp_change) < 3) |>
  knitr::kable()
```

```{r}
weather_df |>
  group_by(name) |> 
  mutate(
    lagged_temp = lag(tmax),
    temp_change = tmax - lagged_temp
  ) |>
  summarise(
    sd_temp_change = sd(temp_change, na.rm = TRUE),
    max_temp_change = max(temp_change, na.rm = TRUE)
  ) |>
  knitr::kable()
```

## Learning assessment

```{r}
library(haven)

pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  )

pulse_df|>
  group_by(visit) |>
  summarise(
    mean_bdi = mean(bdi_score, na.rm = TRUE)
  ) |>
  knitr::kable(digits = 1)
```

## FAS data

```{r message=FALSE, warning=FALSE}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(
    group, into = c("dose", "tx_day"), sep = 3)

pups_df =
  read_csv("data/FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names()

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number")
```

Create a table that we care about:

```{r message=FALSE, warning=FALSE}
fas_df |> 
  group_by(dose, tx_day) |> 
  drop_na(dose) |> 
  summarize(
    mean_pivot = mean(pd_pivot, na.rm = TRUE)
  ) |>
  knitr::kable()

fas_df |> 
  group_by(dose, tx_day) |> 
  drop_na(dose) |> 
  summarize(
    mean_pivot = mean(pd_pivot, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = tx_day, 
    values_from = mean_pivot) |> 
  knitr::kable(digits = 3)
```





